### ISSUE TITLE
Add material core to sandbox

### ISSUE THREAD

**Issue by timrobertson100** [gbif/rs.gbif.org#105]
In the SPNCH workshop we will have a hands-on exercise to map data. One track of that will be mapping Material to Darwin Core Archives in the Sandbox (another to a Frictionless model which is yet to be defined).

To bring DwC-A closer to the work on the model, we'd like to introduce a Material core to use instead of Occurrence which is a layer of confusion. This resurrects and will replace previous ideas with the [MaterialSample core](https://rs.gbif.org/sandbox/core/dwc_material_sample.xml) which never made it to production.

This will be largely similar to Occurrence core, but removing those fields NOT specific to Material.

@tucotuco - can you please confirm `Material` and `materialID` as the preference over the MaterialSample terminology current in DwC, knowing it will align better with the forthcoming model?

**Comment by tucotuco** [comment]
Confirmed to use Material and materialID for this. 

Clarification, do you mean, "This will be largely similar to Occurrence core, but removing those fields NOT specific to Material"?

**Comment by timrobertson100** [comment]
Thanks - corrected

**Comment by dagendresen** [comment]
Notice that [MaterialEntity](https://github.com/tdwg/material-sample/blob/main/review%20package/MaterialEntity.md) and [materialEntityID](https://github.com/tdwg/material-sample/blob/main/review%20package/materialEntityID.md) are close to be proposed

**Comment by tucotuco** [comment]
@timrobertson100 We may save ourselves some hassle by going with MaterialEntity and aligning with the Task Group proposal. There were arguments against Material as being both a noun and an adjective and therefore potentially confusing or misleading.

**Comment by timrobertson100** [comment]
Available in the [sandbox](https://rs.gbif.org/sandbox/core/dwc_material_2023-04-29.xml) and the issue linked above captures the need for IPT v3 support
