### ISSUE TITLE
Downloading data with eMoF extension

### ISSUE THREAD

**Issue by lhmarsden** [gbif/rs.gbif.org#112]
When scientists publish Darwin Core Archives, they often need to include an eMoF extension with all the 'other' measurements they take related to their occurrences. With more and more scientists now using Darwin Core Archive, this configuration is becoming more important.

In Norway, the national research council now says that any projects it funds must publish their data following the FAIR data management principles. 

I am often asked how to get data out of a Darwin Core Archive. For events and occurrences, this is quite easy. However, for eMoF is not particularly easy to work with. Ideally, one would be able to scan through the measurementType column, find all unique 'parameters' and create one column per parameter that can be included within the 'SIMPLE' CSV that one can download.

I don't think this should be too hard to implement either.

![image](https://github.com/gbif/rs.gbif.org/assets/60346517/3980e88b-81b3-46ae-9be4-c2771def3e71)

Currently, one is not getting all the data when they hit download. And I don't think one is warned about the data one is not getting either, which is potentially problematic. 

This might expand to other extensions. Are data from all GBIF registered extensions included in the 'SIMPLE' download?

**Comment by MattBlissett** [comment]
Thanks,

Extension data can now be downloaded through the API — for adding this to the website see https://github.com/gbif/portal16/issues/1910

API documentation: https://techdocs.gbif.org/en/data-use/api-downloads#verbatimextensions

"Flattening" the data as you describe isn't really an option — one occurrence might have many measurements, and we'd lose that structure if we tried to add this to the simple-format downloads.
