### ISSUE TITLE
Why is scientificName part of the resourceRelationship extension?

### ISSUE THREAD

**Issue by peterdesmet** [gbif/rs.gbif.org#12]
I noticed `scientificName` is part of http://rs.gbif.org/extension/dwc/resource_relation.xml (last term):

https://github.com/gbif/rs.gbif.org/blob/4cabf67cd87748572d5cf8689d65636444a5ad94/extension/dwc/resource_relation.xml#L20

Why has this been added? Is it to more easily define relationships with species (cf. `associatedTaxa`), like pollinators? Is it in use? It is not part of the official [Darwin Core resourceRelationShip extension](http://rs.tdwg.org/dwc/terms/index.htm#relindex).

**Comment by mdoering** [comment]
That originates from the old google code site and I cannot say why that is there:
https://github.com/gbif/rs.gbif.org/blame/master/extension/dwc/resource_relation.xml

It seems wrong to me and I would argue to remove it

**Comment by peterdesmet** [comment]
I agree. Can you check if it is in use for any of the GBIF-registered datasets?

**Comment by peterdesmet** [comment]
Note, for the use case where someone wants to add a relationship between a core Taxon record with a scientificName, without listing that name anywhere, you can use:

```
resourceRelationshipID = "relationship1"
resourceID = "taxon1"^^dwc:Taxon
relatedResourceID = "scientific name of my pollinator species" # Alternative for scientificName
relationshipOfResource = "is pollinator of"
```

And does not have to rely on `scientificName`.
