### ISSUE TITLE
redirect needed for http://rs.gbif.org/terms/1.0/Types

### ISSUE THREAD

**Issue by tucotuco** [gbif/rs.gbif.org#120]
See https://github.com/tdwg/dwc/issues/495.

**Comment by MattBlissett** [comment]
http://rs.gbif.org/terms/1.0/TypesAndSpecimen does redirect, and is the RowType given in the extension.

Did http://rs.gbif.org/terms/1.0/Types ever exist?

**Comment by tucotuco** [comment]
I don't know, but it is what is given in the DwC Text Guide. I can change the Text Guide to maximize consistency. Thanks @MattBlissett
