### ISSUE TITLE
improve findability of this repo

### ISSUE THREAD

**Issue by sformel-usgs** [gbif/rs.gbif.org#146]
I struggle to remember that many DwC extensions are maintained through this repo.  When I search GBIF repositories for 'extensions', 'Darwin Core', or 'DwC', this repo doesn't come up. Would it be possible to add these terms to the repo description to help make this repo more findable?

**Comment by timrobertson100** [comment]
Just for related info...

With changes that will emerge from the GBIF data model one idea being considered is to have the schemas managed within Darwin Core itself. This would have many benefits (e.g. a more shared governance) and also some implications that might reduce agility (e.g. relying on shared governance procedures).
