### ISSUE TITLE
New auto-publishing options

### ISSUE THREAD

**Issue by edalcin** [gbif/rs.gbif.org#148]
Hi folks,

I would like to suggest a new set of options for "auto-publishing":

- TurnOff
- Daily
- Weekly
- Biweekly (new)
- Monthly
- Quarterly (new)
- Biannually
- Annually

Depending on the dynamic and size of your collection, those new additions will come in handy.

**Comment by MattBlissett** [comment]
https://eml.ecoinformatics.org/schema/eml-dataset_xsd#MaintenanceType_maintenanceUpdateFrequency

There are a few extra values in EML which we don't yet have in the vocabulary.

**Comment by mike-podolskiy90** [comment]
I believe we don't miss any here https://rs.gbif.org/sandbox/vocabulary/eml/update_frequency_2_2.xml

**Comment by mike-podolskiy90** [comment]
So, since we just reflect EML values, should we just move the new version to production on close this one?

**Comment by mike-podolskiy90** [comment]
Also related https://github.com/gbif/rs.gbif.org/issues/82 (russian translations)

**Comment by MattBlissett** [comment]
Yes, I think that's fine.
