### ISSUE TITLE
add taxonID to the Vernacular Names extension

### ISSUE THREAD

**Issue by CecSve** [gbif/rs.gbif.org#149]
The ID that should link to the Taxon Core entry is not mentioned in the [Vernacular Names](https://rs.gbif.org/extension/gbif/1.0/vernacularname.xml) extension although this is what would enable the link between the core and the extension. Could it please be added based on the [DWC definition](https://dwc.tdwg.org/terms/#dwc:taxonID)?

**Comment by MattBlissett** [comment]
The link to the core is made using the field specified by `<coreid>` in the `<extension>` definition. It's entirely internal data of the Darwin Core Archive, and doesn't need to be a term.

**Comment by CecSve** [comment]
Thank you that makes sense. I still think it should be clear to less technical users that the table must have an ID to link to the core, so I have made a new suggestion https://github.com/gbif/rs.gbif.org/issues/150
