### ISSUE TITLE
Merge pull request for Zooarch

### ISSUE THREAD

**Issue by tucotuco** [gbif/rs.gbif.org#17]
The following pull request constitutes a revision of the ChronometricDate extension, which makes it ready for use in production. Can this pull request please be merged and the extension moved out of the sandbox and into production?

Thank you.

https://github.com/gbif/rs.gbif.org/pull/14

**Comment by mdoering** [comment]
@tucotuco the terms used in this extension use the regular dwc namespace. But I fail to find any of these new terms, e.g. ageUncertaintyInYears in http://rs.tdwg.org/dwc/terms/index.htm

I am not sure if we should move the extension into production in that case. Feels it should stay in sandbox or be using a different namespace, dont you think?

**Comment by mdoering** [comment]
The rowType is also not even present in the DwC repo, neither in code nor issues:
https://github.com/tdwg/dwc/search?q=ChronometricDate

**Comment by tucotuco** [comment]
Created fixes for the two issues noted by Markus and issued a renewed pull request.

**Comment by mdoering** [comment]
Thanks John, that looks good to me indeed and Im going to merge and place it in prod now
