### ISSUE TITLE
Content is different when rendered locally

### ISSUE THREAD

**Issue by peterdesmet** [gbif/rs.gbif.org#2]
I have forked this repo because I want to suggest some changes, but when I render the repository locally (with `python -m SimpleHTTPServer`), I get some differences between my local version and the one on http://rs.gbif.org/

For example: http://rs.gbif.org/vocabulary/gbif/occurrence_status.xml

![online](https://cloud.githubusercontent.com/assets/600993/14915314/322b138c-0e12-11e6-90a0-690a47ab7cd4.png)

Shows the definitions, while my local version:

![local](https://cloud.githubusercontent.com/assets/600993/14915320/3e06fb12-0e12-11e6-90ad-e53d00021d49.png)

Only has links to a spreadsheet.

I assume running as a static file server is not enough? (I also notice some differences in showing the directory tree)

It would be really useful though if all the content was included in this repository, rather than being pulled in from a Google Spreadsheet. It would make making suggestions via pull request possible.

**Comment by timrobertson100** [comment]
If you look at this line, you can see it is not pulling from the spreadsheet.  I'm not saying this isn't an issue, but is it an XSD styling issue perhaps?
  https://github.com/gbif/rs.gbif.org/blob/master/vocabulary/gbif/occurrence_status.xml#L11

Please can you view your page source and verify?

**Comment by peterdesmet** [comment]
Hmm, my source has:

    <concept dc:identifier="present" dc:URI="http://rs.gbif.org/vocabulary/gbif/occurrence_status/present"  dc:issued="2009-10-02" dc:description="http://spreadsheets.google.com/pub?key=tVs-UWMXnkD3slwIE8T336w&amp;gid=3">

**Comment by mdoering** [comment]
then its not up to date :)

**Comment by peterdesmet** [comment]
Don't get it, I checked it out an hour ago. Will investigate.

**Comment by peterdesmet** [comment]
Got it, I was looking at a fork at inbo, rather than my personal account.

**Comment by peterdesmet** [comment]
Thanks! Any idea why I have no styling on the directory tree?

![screen shot 2016-04-29 at 15 40 53](https://cloud.githubusercontent.com/assets/600993/14917748/d8d250de-0e20-11e6-979a-3daa1a393ec6.png)

**Comment by mdoering** [comment]
yes, thats an apache configuration we run. Ive added it to the repo here: https://github.com/gbif/rs.gbif.org/blob/master/virt_rs.conf
