### ISSUE TITLE
Why is there no institutionCode in the taxon core?

### ISSUE THREAD

**Issue by peterdesmet** [gbif/rs.gbif.org#20]
In the mapping of the checklist dataset, we added `institutionCode` to the taxon core (see https://github.com/trias-project/rinse-registry-checklist/issues/9), but were surprised to see it is not included in the taxon core: http://rs.gbif.org/core/dwc_taxon_2015-04-24.xml

What is the reasoning not to include this generic record-level term in the taxon core? It was also missing from the event core, but that has been updated: https://github.com/gbif/rs.gbif.org/pull/5

/cc @lienreyserhove

**Comment by MattBlissett** [comment]
InstitutionCode:

> "The name (or acronym) in use by the institution having custody of the object(s) or information referred to in the record.'

dcterms:rightsHolder:

>  "A person or organization owning or managing rights over the resource."

I think the reason institutionCode isn't part of the taxon core is that term was thought to apply to specimens and observation data.

**Comment by tucotuco** [comment]
I can see why one would think so, but there is nothing actually saying so. It's a record-level term, so it seems reasonable to me to include.

**Comment by MattBlissett** [comment]
I've added the two terms institutionCode and institutionID.
