### ISSUE TITLE
Add regional red list statuses to IUCN threat status vocabulary

### ISSUE THREAD

**Issue by peterdesmet** [gbif/rs.gbif.org#22]
The [current vocabulary for threat status](http://rs.gbif.org/vocabulary/iucn/threat_status.xml) includes the 9 IUCN Red list categories. I don't know the best resource for these, but the link used on the vocab [returns a 404](http://www.iucn.org/about/work/programmes/species/red_list/resources/technical_documents/authority_files/). Wikipedia links to https://en.wikipedia.org/wiki/IUCN_Red_List#cite_note-11 (Figure 2.1)

1. Extinct (EX)
1. Extinct in the Wild (EW)
1. Critically Endangered (CR)
1. Endangered (EN)
1. Vulnerable (VU)
1. Near Threatened (NT)
1. Least Concern (LC)
1. Data Deficient (DD)
1. Not Evaluated (NE)

These are global statuses. For doing "Regional Red List Assessments" and publishing these as **regional** red list datasets to GBIF (a common use case), there are two additional categories (in bold below), also adopted by IUCN (with actually a good page to reference: https://www.iucnredlist.org/about/regional):

1. Extinct (EX)
1. Extinct in the Wild (EW)
1. **Regionally Extinct (RE)**
1. Critically Endangered (CR)
1. Endangered (EN)
1. Vulnerable (VU)
1. Near Threatened (NT)
1. Least Concern (LC)
1. Data Deficient (DD)
1. **Not Applicable (NA)**
1. Not Evaluated (NE)

Can these two official statuses be added to the vocabulary at http://rs.gbif.org/vocabulary/iucn/threat_status.xml? Also, for easier browsing, could the categories in the vocabulary be listed in the order used by IUCN (i.e. as in this issue)?

**Comment by mdoering** [comment]
You can get the official RedList resources here now:
https://www.iucnredlist.org/resources/grid

In particular the *IUCN Red List categories and criteria, version 3.1, second edition* which I also [attached](https://github.com/gbif/rs.gbif.org/files/2652731/RedList.categories.v3.1-2.pdf): https://portals.iucn.org/library/sites/library/files/documents/RL-2001-001-2nd.pdf

There is no notion of a regional status:
[RedList categories v3.1-2.pdf]()
<img width="617" alt="screenshot 2018-12-06 at 11 39 18" src="https://user-images.githubusercontent.com/327505/49579069-9c016280-f94b-11e8-8a61-cbd1bbcbb640.png">

But from your regional link the scheme is extended indeed:
![content_categories_chart_regional_v3](https://user-images.githubusercontent.com/327505/49579194-eb479300-f94b-11e8-9420-692a17c56a33.png)

I will add those right now.

PS: There are also other assessment "schemes" that might be interesting: 
https://www.iucnredlist.org/resources/classification-schemes

**Comment by mdoering** [comment]
Fixed in https://github.com/gbif/rs.gbif.org/commit/66633af154727dab82ec84f60a6f20b77b04ef37
will be online in a few hours

**Comment by peterdesmet** [comment]
Awesome, thanks!
