### ISSUE TITLE
Add source to speciesProfile

### ISSUE THREAD

**Issue by peterdesmet** [gbif/rs.gbif.org#24]
Can the term `source` be added to the [Species Profile](http://rs.gbif.org/extension/gbif/1.0/speciesprofile.xml) extension, so we can credit our sources just like in the [Distribution](http://rs.gbif.org/extension/gbif/1.0/distribution.xml) and [Description](http://rs.gbif.org/extension/gbif/1.0/description.xml) extensions?

**Comment by thomasstjerne** [comment]
Hi @peterdesmet 
This seems like a good suggestion. Can I ask you to do a pull request?
You should
1. Duplicate this file: https://github.com/gbif/rs.gbif.org/blob/master/extension/gbif/1.0/speciesprofile.xml
And append the current date to duplicate file name, i.e.  speciesprofile_YYYY-MM-DD.xml
2. In the duplicate add the "source" term
3. Do a copy of the new version into the sandbox: https://github.com/gbif/rs.gbif.org/tree/master/sandbox/extension
4. Do the pull request

Once you have done the pull request, we will review and merge it and we should be done.
Let me know if you need any help.

Best
Thomas

**Comment by peterdesmet** [comment]
Thanks, PR created #25

**Comment by peterdesmet** [comment]
Now that #25 is merged and available in [sandbox](http://rs.gbif.org/sandbox/extension/speciesprofile_2019-01-29.xml), what is the way forward to get it into production?

**Comment by peterdesmet** [comment]
Thanks! Is there anything that needs to happen before the IPT recognizes there is an updated version that can be installed?
