### ISSUE TITLE
DOUBTFUL missing from taxonomic_status

### ISSUE THREAD

**Issue by peterdesmet** [gbif/rs.gbif.org#26]
I noticed the term `DOUBTFUL` used throughout GBIF is missing from http://rs.gbif.org/vocabulary/gbif/taxonomic_status.xml

**Comment by MattBlissett** [comment]
As seen in our API at https://gbif.github.io/gbif-api/apidocs/org/gbif/api/vocabulary/TaxonomicStatus.html

@mdoering, is there any reason not to add `DOUBTFUL`?

**Comment by mdoering** [comment]
no reason at all!
