### ISSUE TITLE
Is it "nomen dubimum" or "nomen dubium"

### ISSUE THREAD

**Issue by peterdesmet** [gbif/rs.gbif.org#28]
I only find information for [Nomen dubium](https://en.wikipedia.org/wiki/Nomen_dubium) and it is also referred as such in the description for http://rs.gbif.org/vocabulary/gbif/nomenclatural_status.xml:

> A name of uncertain sense, of doubtful validity. E.g. the name Encephalartos tridentatus (Willdenow) Lehmann (Pugillus 6, 1834) is a **nomen dubium** which may refer to several species of Encephalartos or Macrozamia. ICZN: doubtful or dubious names, names which are not certainly applicable to any known taxon or for which the evidence is insufficient to permit recognition of the taxon to which they belong. May possess availability conducive to uncertainty and instability. Also 'names under enquiry': NOMEN INQUIRENDUM (NOMINA INQUIRENDA).

Yet, the term used in the vocab is `dubimum`. If that is actually the correct term, can `nomen dubium` be added as an alternative. (`nomina dubia` already is).

**Comment by bart-v** [comment]
Its' wrong, look at the example :)

> E.g. the name Encephalartos tridentatus (Willdenow) Lehmann (Pugillus 6, 1834) is a nomen **dubium**

Looks like nobody ever used this...hahah

**Comment by timrobertson100** [comment]
I'm not entirely sure it is a typo @bart-v as seems to be used in several places (See below). It has certainly been used (quite a lot I'd expect). We need someone familiar with latin to explain though...

@peterdesmet - I see no reason why it couldn't have a synonym added. Can you please do a PR?

Examples I find:
http://eumycetozoa.com/data/abbreviations.php

https://books.google.dk/books?id=C7HMZcEgovAC&pg=PA9&lpg=PA9&dq=%22dubimum%22&source=bl&ots=eyTwsGnVFn&sig=ACfU3U0HyqwwRq9Z7Ei7-QgpDsengWAIsA&hl=en&sa=X&ved=2ahUKEwj4xJWd_pzgAhWD8ywKHcK7BDoQ6AEwAXoECAMQAQ#v=onepage&q=%22dubimum%22&f=false

https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/doc/irmng-status-values.md

**Comment by bart-v** [comment]
It looks like IRMNG was the source of this, indeed.
We have fixed 26 entries to the correct status on http://www.irmng.org Most of them had also "nom. dub." as free text.

**Comment by peterdesmet** [comment]
So, in the vocab, we should change:

1. `dubium` as official term
2. `dubimum` as alternative
3. `nomen dubium` as alternative

If I do a PR, do you want this as a new version (`_2019-02-06.xml) of the vocab?

**Comment by thomasstjerne** [comment]
> If I do a PR, do you want this as a new version (`_2019-02-06.xml) of the vocab?

Yes, please

**Comment by mdoering** [comment]
Do we version vocabularys too? I thought we never did

**Comment by peterdesmet** [comment]
You do: http://rs.gbif.org/vocabulary/gbif/rank_2015-04-24.xml

Question: for any of the listed _alternatives_, will GBIF map that to the accepted term upon harvesting?

**Comment by mdoering** [comment]
Hm, apparently we recommend to: https://github.com/gbif/rs.gbif.org/blob/master/versioning.md# 

This is very new to me, I’ve never versioned any vocabularies as they were originally designed to be mutable. Sure this is needed and we are not unnecessarily piling up versions? We must then also update all extensions, even externally hosted ones, to use the new vocab. I have also doubts the IPT can handle several vocab versions at the same time in case different extensions reference different versions of the same vocabulary.

**Comment by timrobertson100** [comment]
My understanding is not today.

The simple vocabulary server being incorporated in the registry now will enable that though for occurrence records. ETA Q2 2019 I’d predict. I’d expect checklists to take longer to adopt since all effort is on COL+ right now.

**Comment by peterdesmet** [comment]
@timrobertson100 so we have to use the accepted term in our mapping (thus losing subtleties) for now?

**Comment by mdoering** [comment]
I don‘t think we read any of the IPT xml vocabs when interpreting checklists. But we have parsers for all of these enums, eg rank, that are aware of far more alternatives: 
https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/rank.tsv

Its highly redundant, but we decided early on that its better to rely on local and strongly versioned resource files to have preditcable results than reading external resources

**Comment by peterdesmet** [comment]
@thomasstjerne PR made at #29
