### ISSUE TITLE
Add comments attribute to extension schema

### ISSUE THREAD

**Issue by tucotuco** [gbif/rs.gbif.org#45]
Darwin Core now supports comments separate from the term description and from examples. It would be extremely useful to propagate these comments in extension definition, as they provide recommendations on usage. The alternative now is to combine either description and comments (thus obfuscating the normative term definition) or to combine comments and examples (also not ideal).

Recommend to add the follow at the insert point in the schema given below:

https://github.com/gbif/rs.gbif.org/blob/8bf7d813cda2aed77c7541ce3ce7215f9dbca389/schema/extension.xsd#L37

<xs:attribute name="comments" type="xs:string">
  <xs:annotation>
    <xs:documentation>Recommendations for the content for the property. </xs:documentation>
  </xs:annotation>
</xs:attribute>

While we're at it, it would be good to change the examples documentation as well, to:

<xs:attribute name="examples" type="xs:string">
  <xs:annotation>
    <xs:documentation>Example content for the property. If multiple examples are given, separate them with ' | '.</xs:documentation>
  </xs:annotation>
</xs:attribute>

**Comment by tucotuco** [comment]
While we are at it, it would also be good to have authors and contact info.

**Comment by tucotuco** [comment]
Ready for review in https://github.com/gbif/rs.gbif.org/pull/71.

**Comment by MattBlissett** [comment]
This is now merged into the sandbox.
