### ISSUE TITLE
Update chronometric age in production

### ISSUE THREAD

**Issue by timrobertson100** [gbif/rs.gbif.org#49]
In order to support the TDWG ratification of the chronometric dwc extension work @tucotuco requests that we move the most recent chrono extension into production replacing the existing one. The datasets using it will be updated and used as evidence of use in support during the ratification process.

**Comment by timrobertson100** [comment]
Blocked until the outcome of https://github.com/tdwg/chrono/issues/13 is decided

**Comment by tucotuco** [comment]
This can be closed.
