### ISSUE TITLE
Update MIxS namespace in dna-derived-data exstention.

### ISSUE THREAD

**Issue by ramonawalls** [gbif/rs.gbif.org#51]
https://github.com/gbif/rs.gbif.org/blob/master/sandbox/extension/dna_derived_data.xml uses http://gensc.org/ns/mixs/terms/ as the namespace for MIxS terms. Please note that per https://github.com/GenomicsStandardsConsortium/mixs-rdf/issues/2#issuecomment-657666511 we will be using `https://w3id/gensc/terms/` for the MIxS namespace, with a seven digit opaque ID for each term. We hope to have those term ID released by January 2021. 

There are several old namespaces floating around for MIxS terms, but they don't all resolve and none are authoritative at this time. We are trying to fix this. See GenomicsStandardsConsortium/mixs-rdf#31.

**Comment by mdoering** [comment]
https://w3id/gensc/terms/ looks like an odd IRI to me. It is invalid even, isn't it?
https://w3id/gensc/1234567 seems more appropriate.

**Comment by thomasstjerne** [comment]
@ramonawalls  Are these IDs those in the `MIXS` column in the [MIxS v5 template](http://press3.mcs.anl.gov/gensc/files/2020/02/mixs_v5.xlsx) ?

E.g. the field `experimental_factor` should be `https://w3id/gensc/terms/0000008`?

We simply processed that template, so I can update it from there if the information is already present.

**Comment by ramonawalls** [comment]
> https://w3id/gensc/terms/ is an odd and invalid IRI that should not be used.
> https://w3id/gensc/1234567 seems more appropriate.

We need several namespaces within gensc, for clarity, thus the /terms. We could just use the base namespace for the terms, but I think buidling resolvers will be easier if we use the sub-namespaces. I can bring this up with our group.

**Comment by ramonawalls** [comment]
> @ramonawalls Are these IDs those in the `MIXS` column in the [MIxS v5 template](http://press3.mcs.anl.gov/gensc/files/2020/02/mixs_v5.xlsx) ?
> 
> E.g. the field `experimental_factor` should be `https://w3id/gensc/terms/0000008`?
> 
> We simply processed that template, so I can update it from there if the information is already present.

Not yet. They will only take affect with MIxS 6. I could point you at the spread sheet with the IDs now, but since they are not released yet, that would be dangerous (i.e. some things are likely to change).

**Comment by ramonawalls** [comment]
Also note correction: Namespace should be `https://w3id.org/gensc/terms/`

**Comment by timrobertson100** [comment]
Thanks @frafra  
The outstanding issue is what namespace to scope the concepts in the controlled vocabularies, which we are discussing now. Once that is clear we expect this can be released and we'll do all we can to make this happen as soon as possible.

**Comment by MattBlissett** [comment]
The extension has now been released, so it should now be possible to use it in the IPT.
