### ISSUE TITLE
Move chronometric age to production

### ISSUE THREAD

**Issue by timrobertson100** [gbif/rs.gbif.org#65]
The [latest chronometric age extension](https://rs.gbif.org/sandbox/extension/ChronometricAge_2021-03-27.xml) that sits in the sandbox is ratified by TDWG and to be moved to production for GBIF-network use.

This requires:

- [x] A final check it works as expected in a test IPT (e.g. ipt.gbif.org)
- [x] Verification from @tucotuco of where it should go - I presume this is in the `extensions/dwc` folder?
- [x] Copied into the production extension folder
- [x] Remove the older versions of the extension from the sandbox (housekeeping)

**Comment by tucotuco** [comment]
Confirmed that the file should go in the extensions/dwc folder. Eveything in extemsions/zooarchnet is now obsolete.

**Comment by tucotuco** [comment]
Test publication with new extension successful. All looks good.

https://ipt.gbif.org/resource?r=flarch_zooarch_parnell_feature1_test

**Comment by timrobertson100** [comment]
You should be all set @tucotuco 
https://rs.gbif.org/extension/dwc/
