### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by mjy** [gbif/rs.gbif.org#7]
When I visit this repository (https://github.com/gbif/rs.gbif.org) then
 
* I do not see a document (CONTRIBUTING.md) indicating whether pull requests are accepted
* I do not know whether the org wants a particular format of pull request
* I do not know whether the org wants a particular format of filed issues

**Comment by timrobertson100** [comment]
I think this ticket was opened by a bot, but still CONTRIBUTIONS.MD now exists.

**Comment by peterdesmet** [comment]
@timrobertson100 can you please call it `CONTRIBUTION.md` so it is automatically detected by GitHub (e.g. when opening an issue)? See e.g. https://github.com/ropensci/wateRinfo/tree/master/.github To organize similar files, you can include this a `.github` directory rather than cluttering the root.

**Comment by timrobertson100** [comment]
I presume you meant `CONTRIBUTING.md`?

Want to do a PR for that?

**Comment by peterdesmet** [comment]
Ah, yes, that's what I meant. 😁You'll be able to do this quicker than me probably, but sure: do you prefer it in the `.github` dir or root?
