### ISSUE TITLE
http://rs.gbif.org/terms/1.0/DNADerivedData is not available

### ISSUE THREAD

**Issue by frafra** [gbif/rs.gbif.org#70]
Broken reference: http://rs.gbif.org/terms/1.0/DNADerivedData

https://github.com/gbif/rs.gbif.org/blob/89f45962dfe2e1e42a1007493558eb88166bdb85/extension/gbif/1.0/dna_derived_data_2021-07-05.xml#L10

**Comment by thomasstjerne** [comment]
@frafra The rowType is just an identifier to be used in an DwC meta.xml to define the schema of the data. 
This schema is the actual data description: rs.gbif.org/extension/gbif/1.0/dna_derived_data_2021-07-05.xml

**Comment by MattBlissett** [comment]
I am working on adding resolution as part of #61.

**Comment by MattBlissett** [comment]
This should now resolve correctly.
