### ISSUE TITLE
Retire unused extensions in the sandbox

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/rs.gbif.org#74]
We need to retire the OBIS MBG extensions that are in the GBIF sandbox. The OBIS community has gone a different direction of using the extended measurement or fact extension and those test extensions have not been adopted by the community. Please let me know if there is work I need to do to make that happen. Thank you!

**Comment by timrobertson100** [comment]
Thanks @albenson-usgs 
Should be done, and will be reflected in IPTs in the coming minutes.
