### ISSUE TITLE
When will updated to DwC be available in production?

### ISSUE THREAD

**Issue by peterdesmet** [gbif/rs.gbif.org#80]
I notice that e.g. the update ResourceRelationship extension is available in the sandbox: https://github.com/gbif/rs.gbif.org/blob/master/sandbox/extension/resource_relationship_2021-08-16.xml

When will this and other updates to Darwin Core be available for production use?

**Comment by tucotuco** [comment]
With the Darwin Core Maintenance Group public meeting coming up on 2021-11-03 and 2021-11-11, I expect this will be the most common question people have. Is there any chance we'll be able to tell them, "They are now in production."?

**Comment by dagendresen** [comment]
Also curious about the status for moving the sandbox MoF extension with the dwciri terms into production
https://rs.gbif.org/sandbox/extension/measurements_or_facts.xml

**Comment by MattBlissett** [comment]
Sorry Dag, this has been overlooked.  @tucotuco generated the new extensions (i.e. https://rs.gbif.org/sandbox/extension/measurements_or_facts_2021-08-16.xml) using a script and without the DWCIRI terms, and that's should be live in early January, as development on the interpretation side is in progress.
