### ISSUE TITLE
Can't install schema extension dna_derived_data

### ISSUE THREAD

**Issue by raffael-mnhn** [gbif/rs.gbif.org#89]
```
An error occurred while trying to install extension http://rs.gbif.org/extension/gbif/1.0/dna_derived_data_2021-07-05.xml.

Can't parse local extension file: Error at line 138 char 27: An error occurred while trying to install vocabulary https://rs.gbif.org/vocabulary/mixs/biotic_relationship.xml.
```
Trying to GET `https://rs.gbif.org/vocabulary/mixs/biotic_relationship.xml` returns 404.

@mnhn-paul

**Comment by MattBlissett** [comment]
Sorry, there was an error in the extension.  Would you try again please?

**Comment by mnhn-paul** [comment]
@MattBlissett I just tried and it is working now.  thanks a lot

![image](https://user-images.githubusercontent.com/26623703/155318638-5982c685-0f92-4dd9-9ba3-02b9504668aa.png)
